const KEY='chinese-final-drill-v1',CFG='chinese-final-drill-sync';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],day=()=>new Date().toISOString().slice(0,10);
const fresh=()=>({version:1,cards:{},streak:{last:'',count:0},updatedAt:new Date().toISOString()});
let state=load(),lessons=new Set(['5','6','7','8','9','10','11']),queue=[],card,mode,done=0,pushTimer;
function load(){try{return{...fresh(),...JSON.parse(localStorage.getItem(KEY)||'{}')}}catch{return fresh()}}
function save(){state.updatedAt=new Date().toISOString();localStorage.setItem(KEY,JSON.stringify(state));stats()}
function norm(x){return String(x||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[\s·・,，。.!！?？/／()（）〜～-]/g,'')}
const marks={a:'āáǎà',e:'ēéěè',i:'īíǐì',o:'ōóǒò',u:'ūúǔù',v:'ǖǘǚǜ','ü':'ǖǘǚǜ'};
function toneNumbers(s){return s.toLowerCase().replace(/u:/g,'v').split(/\s+/).map(x=>{let m=x.match(/^([a-züv]+)([1-5])$/);if(!m)return x;if(m[2]==='5')return m[1].replace('v','ü');let y=m[1],n=+m[2]-1,i=y.search(/[ae]/);if(i<0&&y.includes('ou'))i=y.indexOf('o');if(i<0){let vs=[...y.matchAll(/[aeiouvü]/g)];i=vs.length?vs[vs.length-1].index:-1}return i<0?y:y.slice(0,i)+(marks[y[i]]?.[n]||y[i])+y.slice(i+1)}).join(' ')}
function correct(input){if(mode==='hanzi-pinyin')return norm(toneNumbers(input))===norm(card.pinyin);if(mode==='ja-hanzi')return norm(input)===norm(card.hanzi);return norm(input)===norm(card.ja)||card.ja.split(/[、,]/).some(x=>norm(input)===norm(x))}
function due(v){let x=state.cards[v.id];return !x?.due||new Date(x.due)<=new Date()}
function stats(){$('#dueCount').textContent=VOCAB.filter(due).length;let n=Object.keys(state.cards).length;$('#learnedCount').textContent=n;$('#streakCount').textContent=state.streak.count||0;$('#progressBar').style.width=`${n/VOCAB.length*100}%`}
function chips(){for(let n of lessons){let b=document.createElement('button');b.className='chip on';b.textContent=`第${n}課`;b.onclick=()=>{lessons.has(n)?lessons.delete(n):lessons.add(n);b.classList.toggle('on')};$('#lessonChips').append(b)}}
function start(){if(!lessons.size)return alert('課を1つ以上選んでください');let pool=VOCAB.filter(v=>lessons.has(v.lesson)),a=pool.filter(due),b=pool.filter(v=>!due(v));a.sort((x,y)=>(state.cards[x.id]?.due||'').localeCompare(state.cards[y.id]?.due||''));b.sort(()=>Math.random()-.5);queue=[...a,...b].slice(0,+$('#sessionSize').value);done=0;$('#home').hidden=true;$('#study').classList.add('active');next()}
function next(){if(!queue.length){$('#study').innerHTML='<div class="prompt"><div><h2>今日の学習完了！</h2><p class="note">おつかれさまでした。履歴は保存済みです。</p><button class="primary" onclick="location.reload()">ホームへ</button></div></div>';return}card=queue.shift();let m=$('#mode').value;mode=m==='mixed'?['ja-hanzi','hanzi-pinyin','hanzi-ja'][Math.random()*3|0]:m;$('#qMeta').textContent=`第${card.lesson}課`;$('#qProgress').textContent=`${done+1}問目`;$('#prompt').textContent=mode==='ja-hanzi'?card.ja:card.hanzi;$('#answerInput').value='';$('#answerInput').placeholder=mode==='hanzi-pinyin'?'ピンイン（ni3 hao3 でも可）':mode==='ja-hanzi'?'簡体字を入力':'日本語を入力';$('#hint').textContent=mode==='hanzi-pinyin'?'声調記号または声調数字で入力':'入力後に答え合わせ';$('#answerForm').hidden=false;$('#result').classList.remove('show');setTimeout(()=>$('#answerInput').focus(),50)}
function check(e){e.preventDefault();let input=$('#answerInput').value.trim();if(!input)return;let ok=correct(input);$('#judge').textContent=ok?'正解！':'答えを確認して自己評価してください';$('#judge').className=ok?'ok':'ng';$('#aHanzi').textContent=card.hanzi;$('#aPinyin').textContent=card.pinyin;$('#aJa').textContent=card.ja;$('#aYours').textContent=input;$('#answerForm').hidden=true;$('#result').classList.add('show')}
function grade(g){let now=Date.now(),x=state.cards[card.id]||{interval:0,ease:2.5,reps:0,lapses:0},minutes;if(g==='again'){x.interval=0;x.lapses++;minutes=1}else if(g==='hard'){x.interval=Math.max(.007,x.interval*.5||.007);minutes=10}else if(g==='good'){x.interval=x.interval<1?1:Math.round(x.interval*x.ease);minutes=x.interval*1440;x.reps++}else{x.ease=Math.min(3,x.ease+.15);x.interval=x.interval<1?3:Math.round(x.interval*x.ease*1.3);minutes=x.interval*1440;x.reps++}x.due=new Date(now+minutes*60000).toISOString();x.last=now;state.cards[card.id]=x;let t=day();if(state.streak.last!==t){let y=new Date(Date.now()-86400000).toISOString().slice(0,10);state.streak.count=state.streak.last===y?(state.streak.count||0)+1:1;state.streak.last=t}done++;save();autoPush();next()}
function openSync(){let c=JSON.parse(localStorage.getItem(CFG)||'{}');$('#token').value=c.token||'';$('#gistId').value=c.gistId||'';$('#settings').showModal()}
async function sync(kind){let c=JSON.parse(localStorage.getItem(CFG)||'{}'),token=$('#token').value||c.token,id=$('#gistId').value||c.gistId;if(!token)throw Error('Tokenを入力してください');let h={Authorization:`Bearer ${token}`,Accept:'application/vnd.github+json','X-GitHub-Api-Version':'2022-11-28'};if(kind==='push'){let body={description:'中国語期末対策ドリル 学習履歴',public:false,files:{'chinese-final-progress.json':{content:JSON.stringify(state,null,2)}}};let r=await fetch(id?`https://api.github.com/gists/${id}`:'https://api.github.com/gists',{method:id?'PATCH':'POST',headers:{...h,'Content-Type':'application/json'},body:JSON.stringify(body)});if(!r.ok)throw Error(`GitHub API ${r.status}`);let j=await r.json();$('#gistId').value=j.id;localStorage.setItem(CFG,JSON.stringify({token,gistId:j.id}));return'クラウドへ保存しました'}if(!id)throw Error('Gist IDを入力してください');let r=await fetch(`https://api.github.com/gists/${id}`,{headers:h});if(!r.ok)throw Error(`GitHub API ${r.status}`);let j=await r.json(),text=j.files['chinese-final-progress.json']?.content;if(!text)throw Error('履歴ファイルがありません');let remote=JSON.parse(text);if(new Date(remote.updatedAt)>new Date(state.updatedAt)){state=remote;save()}return'クラウドから取得しました'}
function autoPush(){let c=JSON.parse(localStorage.getItem(CFG)||'{}');if(!c.token||!c.gistId)return;clearTimeout(pushTimer);pushTimer=setTimeout(()=>sync('push').catch(()=>{}),800)}
function importShareLink(){if(!location.hash.startsWith('#sync='))return false;try{let x=location.hash.slice(6).replace(/-/g,'+').replace(/_/g,'/'),c=JSON.parse(decodeURIComponent(escape(atob(x))));if(!c.token||!c.gistId)throw Error();localStorage.setItem(CFG,JSON.stringify(c));history.replaceState(null,'',location.pathname+location.search);return true}catch{return false}}
async function copyShareLink(){let c={token:$('#token').value,gistId:$('#gistId').value};if(!c.token||!c.gistId)throw Error('先に「今すぐ保存」を押してください');let x=btoa(unescape(encodeURIComponent(JSON.stringify(c)))).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'');await navigator.clipboard.writeText(`${location.origin}${location.pathname}#sync=${x}`);return'共有リンクをコピーしました。別端末で開いてください'}
$('#startBtn').onclick=start;$('#answerForm').onsubmit=check;$$('.grades button').forEach(b=>b.onclick=()=>grade(b.dataset.grade));$('#settingsBtn').onclick=openSync;$('#closeSettings').onclick=()=>$('#settings').close();$('#saveSettings').onclick=()=>{$('#syncStatus').textContent='設定を保存しました';localStorage.setItem(CFG,JSON.stringify({token:$('#token').value,gistId:$('#gistId').value}))};
for(let [id,k] of [['pushBtn','push'],['pullBtn','pull']])$('#'+id).onclick=async()=>{let s=$('#syncStatus');s.textContent='通信中…';try{s.textContent=await sync(k)}catch(e){s.textContent=`エラー: ${e.message}`}};
$('#shareBtn').onclick=async()=>{try{$('#syncStatus').textContent=await copyShareLink()}catch(e){$('#syncStatus').textContent=`エラー: ${e.message}`}};
$('#exportBtn').onclick=()=>{let a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(state,null,2)],{type:'application/json'}));a.download=`chinese-progress-${day()}.json`;a.click();URL.revokeObjectURL(a.href)};
$('#importInput').onchange=async e=>{try{let j=JSON.parse(await e.target.files[0].text());if(!j.cards)throw Error('形式が違います');state=j;save();$('#syncStatus').textContent='読み込みました'}catch(x){$('#syncStatus').textContent=`エラー: ${x.message}`}};
chips();stats();let shared=importShareLink(),cfg=JSON.parse(localStorage.getItem(CFG)||'{}');if(cfg.token&&cfg.gistId)sync('pull').then(()=>{if(shared)alert('共有設定と学習履歴を読み込みました')}).catch(()=>{});
